const genres = [
    "Hành Động", "Tình Cảm", "Hài Hước", "Cổ Trang", "Tâm Lý", "Hình Sự",
    "Chiến Tranh", "Thể Thao", "Võ Thuật", "Viễn Tưởng", "Phiêu Lưu", "Khoa Học",
    "Kinh Dị", "Âm Nhạc", "Thần Thoại", "Tài Liệu", "Gia Đình", "Chính kịch",
    "Bí ẩn", "Học Đường", "Kinh Điển", "Anime & Hoạt Hình", "TV Shows"
];

const countries = [
    "Trung Quốc", "Hàn Quốc", "Nhật Bản", "Thái Lan", "Âu Mỹ", "Đài Loan",
    "Hồng Kông", "Ấn Độ", "Anh", "Pháp", "Canada", "Nga", "Việt Nam"
];

const years = [2026, 2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015];

const moviesData = [
    {
        id: 1,
        title: "Chủ Tịch Tập Sự",
        original: "Reborn Rookie",
        type: "series",
        tags: ["drama", "romance", "dubbed"],
        genre: "Tâm Lý",
        country: "Trung Quốc",
        year: 2026,
        status: "Tập 4/12",
        quality: "HD",
        lang: "Thuyết Minh",
        rating: 7.6,
        views: 291303,
        poster: "https://image.tmdb.org/t/p/w500/lA5fOBqTOQBQ1s9lEYYPmNXoYLi.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
        description: "Một nhân viên trẻ bước vào cuộc cạnh tranh quyền lực khốc liệt, vừa học cách sinh tồn trong công ty vừa tìm lại giá trị thật của mình.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 2,
        title: "Kiều Sở",
        original: "Ashes to Crown",
        type: "series",
        tags: ["drama", "romance"],
        genre: "Cổ Trang",
        country: "Trung Quốc",
        year: 2026,
        status: "Tập 11/24",
        quality: "HD",
        lang: "Vietsub",
        rating: 8.1,
        views: 687238,
        poster: "https://image.tmdb.org/t/p/w500/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/rthMuZfFv4fqEU4JVbgSW9wQ8rs.jpg",
        description: "Từ thân phận thấp bé, Kiều Sở từng bước bước vào triều cục, đối đầu âm mưu và lựa chọn giữa tình yêu với tham vọng.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 3,
        title: "Thần Y Cổ Đại Ở Thành Phố",
        original: "Divine Doctor",
        type: "series",
        tags: ["fantasy", "comedy"],
        genre: "Viễn Tưởng",
        country: "Trung Quốc",
        year: 2026,
        status: "Tập 27/36",
        quality: "HD",
        lang: "Vietsub",
        rating: 7.8,
        views: 518204,
        poster: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
        description: "Một thần y xuyên không đến đô thị hiện đại, dùng y thuật và trí tuệ để phá những vụ án kỳ lạ.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 4,
        title: "Chói Mắt",
        original: "Dazzling",
        type: "series",
        tags: ["romance", "drama"],
        genre: "Tình Cảm",
        country: "Hàn Quốc",
        year: 2026,
        status: "Tập 20/36",
        quality: "HD",
        lang: "Vietsub",
        rating: 8.0,
        views: 403928,
        poster: "https://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg",
        description: "Một chuyện tình nhiều lớp ký ức, nơi những lựa chọn nhỏ khiến cuộc đời hai con người rẽ sang hướng không ngờ.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 5,
        title: "Kẻ Thù Hoàng Gia Của Tôi",
        original: "My Royal Nemesis",
        type: "series",
        tags: ["action", "romance"],
        genre: "Cổ Trang",
        country: "Trung Quốc",
        year: 2026,
        status: "Tập 10/14",
        quality: "HD",
        lang: "Vietsub",
        rating: 7.8,
        views: 731014,
        poster: "https://image.tmdb.org/t/p/w500/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg",
        description: "Hai đối thủ trong hoàng cung phải hợp tác khi âm mưu phản loạn đẩy họ vào cùng một chiến tuyến.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 6,
        title: "He-Man Và Những Chiến Binh Vũ Trụ",
        original: "Masters of the Universe",
        type: "movie",
        tags: ["action", "animation", "cinema"],
        genre: "Hành Động",
        country: "Âu Mỹ",
        year: 2026,
        status: "N/A",
        quality: "HDrip",
        lang: "Vietsub",
        rating: 7.1,
        views: 1851549,
        poster: "https://image.tmdb.org/t/p/w500/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg",
        description: "Một chiến binh trẻ nhận thanh kiếm quyền năng và bước vào cuộc chiến bảo vệ vũ trụ khỏi bóng tối.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 7,
        title: "Cuộc Chiến Sinh Tử II",
        original: "Mortal Kombat II",
        type: "movie",
        tags: ["action", "cinema"],
        genre: "Võ Thuật",
        country: "Âu Mỹ",
        year: 2026,
        status: "N/A",
        quality: "HD",
        lang: "Vietsub",
        rating: 7.3,
        views: 241993,
        poster: "https://image.tmdb.org/t/p/w500/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/gMJngTNfaqCSCqGD4y8lVMZXKDn.jpg",
        description: "Các võ sĩ được triệu tập cho giải đấu định mệnh, nơi thất bại đồng nghĩa với mất cả thế giới.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 8,
        title: "Tình Người Duyên Ma: Nhắm Mak Yêu Luôn",
        original: "Nak Loves Mak Sooo Much!",
        type: "movie",
        tags: ["comedy", "horror", "cinema"],
        genre: "Hài Hước",
        country: "Thái Lan",
        year: 2026,
        status: "N/A",
        quality: "HD",
        lang: "Vietsub",
        rating: 7.0,
        views: 193420,
        poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/ApiBzeaa95TNYliSbQ8pJv4Fje7.jpg",
        description: "Câu chuyện ma hài quen thuộc được kể lại bằng nhịp phim mới, lầy lội hơn nhưng vẫn giữ phần cảm xúc.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 9,
        title: "Thiên Đường Máu",
        original: "Bloody Haven",
        type: "movie",
        tags: ["horror", "cinema"],
        genre: "Kinh Dị",
        country: "Hàn Quốc",
        year: 2026,
        status: "N/A",
        quality: "HD",
        lang: "Vietsub",
        rating: 6.9,
        views: 165842,
        poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
        description: "Một khu nghỉ dưỡng biệt lập trở thành bẫy chết người khi các vị khách phát hiện bí mật dưới lòng đất.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 10,
        title: "Wistoria: Trượng Và Kiếm",
        original: "Wistoria: Wand and Sword",
        type: "series",
        tags: ["animation", "action", "fantasy"],
        genre: "Anime & Hoạt Hình",
        country: "Nhật Bản",
        year: 2026,
        status: "Tập 9/12",
        quality: "HD",
        lang: "Vietsub",
        rating: 8.2,
        views: 376551,
        poster: "https://image.tmdb.org/t/p/w500/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/8rpDcsfLJypbO6vREc0547VKqEv.jpg",
        description: "Một kiếm sĩ không có phép thuật cố gắng chứng minh bản thân trong học viện pháp sư danh giá.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 11,
        title: "Double Helix",
        original: "Double Helix",
        type: "series",
        tags: ["crime", "drama"],
        genre: "Hình Sự",
        country: "Âu Mỹ",
        year: 2026,
        status: "Tập 9/12",
        quality: "HD",
        lang: "Vietsub",
        rating: 7.4,
        views: 224101,
        poster: "https://image.tmdb.org/t/p/w500/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/uKb22E0nlzr914bA9KyA5CVCOlV.jpg",
        description: "Một chuỗi án mạng liên quan đến nghiên cứu gen kéo hai điều tra viên vào mạng lưới che giấu tinh vi.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 12,
        title: "Bài Học Đáng Đời",
        original: "Teach You a Lesson",
        type: "series",
        tags: ["comedy", "drama", "dubbed"],
        genre: "Hài Hước",
        country: "Hàn Quốc",
        year: 2025,
        status: "Hoàn tất (10/10)",
        quality: "HD",
        lang: "Thuyết Minh",
        rating: 8.0,
        views: 1858762,
        poster: "https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
        description: "Một giáo viên kỳ quặc và lớp học bất trị cùng tạo nên những tình huống vừa buồn cười vừa đáng suy ngẫm.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 13,
        title: "Kẻ Đánh Cắp Mặt Trăng",
        original: "Moonlight Thief",
        type: "movie",
        tags: ["action", "crime", "cinema"],
        genre: "Hành Động",
        country: "Âu Mỹ",
        year: 2025,
        status: "N/A",
        quality: "HD",
        lang: "Vietsub",
        rating: 7.5,
        views: 318440,
        poster: "https://image.tmdb.org/t/p/w500/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/6van4BavoNXaZhCPdzLHNQ4Uc8H.jpg",
        description: "Một siêu trộm nhận phi vụ cuối cùng trong thành phố không ngủ, nhưng mục tiêu thật sự lại nằm ngoài bản kế hoạch.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 14,
        title: "Mùa Hè Không Tên",
        original: "Nameless Summer",
        type: "movie",
        tags: ["romance", "drama"],
        genre: "Tình Cảm",
        country: "Hàn Quốc",
        year: 2024,
        status: "N/A",
        quality: "HD",
        lang: "Vietsub",
        rating: 7.7,
        views: 205661,
        poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
        description: "Hai người trẻ gặp nhau trong một mùa hè ngắn ngủi, để rồi những điều chưa kịp gọi tên trở thành ký ức khó quên.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 15,
        title: "Án Mạng Bên Hồ",
        original: "Lakewood Murders",
        type: "series",
        tags: ["crime", "drama"],
        genre: "Hình Sự",
        country: "Anh",
        year: 2025,
        status: "Tập 6/8",
        quality: "HD",
        lang: "Vietsub",
        rating: 8.3,
        views: 438902,
        poster: "https://image.tmdb.org/t/p/w500/2yYP0PQjG8zVqturh1BAqu2Tixl.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg",
        description: "Một vụ án cũ trỗi dậy khi thi thể mới được tìm thấy bên hồ, buộc thị trấn yên bình đối diện quá khứ bị chôn giấu.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 16,
        title: "Robot Biết Yêu",
        original: "Love.exe",
        type: "series",
        tags: ["comedy", "fantasy", "romance"],
        genre: "Hài Hước",
        country: "Nhật Bản",
        year: 2026,
        status: "Tập 8/12",
        quality: "HD",
        lang: "Vietsub",
        rating: 7.9,
        views: 286730,
        poster: "https://image.tmdb.org/t/p/w500/5a4JdoFwll5DRtKMe7JLuGQ9yJm.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
        description: "Một kỹ sư cô độc vô tình kích hoạt thuật toán cảm xúc, kéo theo hàng loạt tình huống dở khóc dở cười.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 17,
        title: "Bóng Tối Dưới Tầng Hầm",
        original: "Below the Basement",
        type: "movie",
        tags: ["horror"],
        genre: "Kinh Dị",
        country: "Âu Mỹ",
        year: 2025,
        status: "N/A",
        quality: "HD",
        lang: "Vietsub",
        rating: 6.8,
        views: 174015,
        poster: "https://image.tmdb.org/t/p/w500/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/9nhjGaFLKtddDPtPaX5EmKqsWdH.jpg",
        description: "Một gia đình chuyển đến căn nhà mới và phát hiện tầng hầm bị niêm phong không phải để bảo vệ người bên ngoài.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 18,
        title: "Biệt Đội Sao Băng",
        original: "Meteor Squad",
        type: "series",
        tags: ["animation", "action", "fantasy"],
        genre: "Anime & Hoạt Hình",
        country: "Nhật Bản",
        year: 2026,
        status: "Tập 5/24",
        quality: "HD",
        lang: "Vietsub",
        rating: 8.0,
        views: 344812,
        poster: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
        description: "Một nhóm học viên sở hữu năng lực thiên thạch phải bảo vệ thành phố trước những cơn mưa sao băng dị biến.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 19,
        title: "Đường Đua Bão Lửa",
        original: "Storm Track",
        type: "movie",
        tags: ["action", "cinema"],
        genre: "Hành Động",
        country: "Hồng Kông",
        year: 2024,
        status: "N/A",
        quality: "4K",
        lang: "Thuyết Minh",
        rating: 7.2,
        views: 256910,
        poster: "https://image.tmdb.org/t/p/w500/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg",
        description: "Một tay đua bị cuốn vào đường dây vận chuyển trái phép và phải dùng tốc độ để cứu người thân khỏi cuộc truy sát.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 20,
        title: "Ngôi Nhà Bên Kia Sông",
        original: "The House Across the River",
        type: "series",
        tags: ["drama", "mystery"],
        genre: "Bí ẩn",
        country: "Thái Lan",
        year: 2025,
        status: "Hoàn tất (12/12)",
        quality: "HD",
        lang: "Vietsub",
        rating: 8.4,
        views: 612884,
        poster: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/5hNcsnMkwU2LknLoru73c76el3z.jpg",
        description: "Sau khi trở về quê, một nhà báo phát hiện ngôi nhà bên kia sông có liên quan đến hàng loạt vụ mất tích.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 21,
        title: "Công Thức Gia Đình",
        original: "Family Recipe",
        type: "series",
        tags: ["comedy", "drama"],
        genre: "Gia Đình",
        country: "Việt Nam",
        year: 2026,
        status: "Tập 14/30",
        quality: "HD",
        lang: "Thuyết Minh",
        rating: 7.6,
        views: 198337,
        poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
        description: "Một quán ăn gia truyền đứng trước nguy cơ đóng cửa khi ba thế hệ trong nhà không ai chịu nhường ai.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 22,
        title: "Hành Tinh Im Lặng",
        original: "Silent Planet",
        type: "movie",
        tags: ["fantasy", "action", "cinema"],
        genre: "Khoa Học",
        country: "Canada",
        year: 2025,
        status: "N/A",
        quality: "HD",
        lang: "Vietsub",
        rating: 7.8,
        views: 389441,
        poster: "https://image.tmdb.org/t/p/w500/34nDCQZwaEvsy4CFO5hkGRFDCVU.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/8rpDcsfLJypbO6vREc0547VKqEv.jpg",
        description: "Một phi hành đoàn mắc kẹt trên hành tinh không có âm thanh, nơi mọi tín hiệu liên lạc đều dẫn đến cùng một tọa độ bí ẩn.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 23,
        title: "Lời Nguyền Hoa Đỏ",
        original: "Red Blossom Curse",
        type: "movie",
        tags: ["horror", "mystery", "cinema"],
        genre: "Kinh Dị",
        country: "Thái Lan",
        year: 2026,
        status: "N/A",
        quality: "HD",
        lang: "Vietsub",
        rating: 7.1,
        views: 301774,
        poster: "https://image.tmdb.org/t/p/w500/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
        description: "Một bó hoa đỏ xuất hiện trước mỗi cái chết, kéo nhóm bạn cũ trở lại bí mật họ từng chôn giấu.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 24,
        title: "Thành Phố Không Ngủ",
        original: "No Sleep City",
        type: "series",
        tags: ["crime", "action"],
        genre: "Hình Sự",
        country: "Hồng Kông",
        year: 2026,
        status: "Tập 12/24",
        quality: "HD",
        lang: "Thuyết Minh",
        rating: 7.9,
        views: 455210,
        poster: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
        description: "Một đội cảnh sát đêm lần theo đường dây rửa tiền hoạt động sau ánh đèn neon của thành phố.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 25,
        title: "Bản Giao Hưởng Cuối",
        original: "The Last Symphony",
        type: "movie",
        tags: ["drama", "romance"],
        genre: "Âm Nhạc",
        country: "Pháp",
        year: 2025,
        status: "N/A",
        quality: "HD",
        lang: "Vietsub",
        rating: 8.1,
        views: 267904,
        poster: "https://image.tmdb.org/t/p/w500/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/yCnJT53HMXAK87xzPAdjdYhZ3JE.jpg",
        description: "Một nhạc trưởng trở lại sân khấu sau biến cố, đối diện bản nhạc dang dở và người từng rời xa ông.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 26,
        title: "Mật Mã Long Thành",
        original: "Dragon City Code",
        type: "series",
        tags: ["action", "fantasy"],
        genre: "Võ Thuật",
        country: "Trung Quốc",
        year: 2026,
        status: "Tập 18/40",
        quality: "HD",
        lang: "Vietsub",
        rating: 8.0,
        views: 529118,
        poster: "https://image.tmdb.org/t/p/w500/1E5baAaEse26fej7uHcjOgEE2t2.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/628Dep6AxEtDxjZoGP78TsOxYbK.jpg",
        description: "Một mật mã cổ dẫn các môn phái vào cuộc tranh đoạt kho báu, nơi kẻ mạnh nhất chưa chắc là người sống sót.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 27,
        title: "Ngày Mai Của Chúng Ta",
        original: "Our Tomorrow",
        type: "series",
        tags: ["romance", "drama"],
        genre: "Tình Cảm",
        country: "Việt Nam",
        year: 2026,
        status: "Tập 9/20",
        quality: "HD",
        lang: "Thuyết Minh",
        rating: 7.5,
        views: 235782,
        poster: "https://image.tmdb.org/t/p/w500/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/7I6VUdPj6tQECNHdviJkUHD2u89.jpg",
        description: "Ba người bạn trưởng thành cùng thành phố, cùng hoài bão, nhưng phải chọn giữa tình yêu và con đường riêng.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 28,
        title: "Thợ Săn Ký Ức",
        original: "Memory Hunter",
        type: "movie",
        tags: ["fantasy", "action", "cinema"],
        genre: "Viễn Tưởng",
        country: "Âu Mỹ",
        year: 2025,
        status: "N/A",
        quality: "4K",
        lang: "Vietsub",
        rating: 7.7,
        views: 411002,
        poster: "https://image.tmdb.org/t/p/w500/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
        description: "Trong tương lai, ký ức có thể bị mua bán, và một thợ săn dữ liệu phát hiện quá khứ của chính mình đã bị đánh cắp.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 29,
        title: "Học Viện Bão Tố",
        original: "Storm Academy",
        type: "series",
        tags: ["animation", "fantasy", "comedy"],
        genre: "Học Đường",
        country: "Nhật Bản",
        year: 2026,
        status: "Tập 7/13",
        quality: "HD",
        lang: "Vietsub",
        rating: 7.8,
        views: 322019,
        poster: "https://image.tmdb.org/t/p/w500/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
        description: "Một học viện đào tạo pháp sư thời tiết rơi vào hỗn loạn khi tân sinh viên vô tình triệu hồi cơn bão cấm.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 30,
        title: "Bữa Tiệc Lúc Nửa Đêm",
        original: "Midnight Dinner",
        type: "movie",
        tags: ["comedy", "drama"],
        genre: "Hài Hước",
        country: "Hàn Quốc",
        year: 2024,
        status: "N/A",
        quality: "HD",
        lang: "Vietsub",
        rating: 7.4,
        views: 189620,
        poster: "https://image.tmdb.org/t/p/w500/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
        description: "Một nhà hàng chỉ mở sau nửa đêm trở thành nơi những con người xa lạ chữa lành bằng món ăn và câu chuyện.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 31,
        title: "Chiến Tuyến Băng Giá",
        original: "Frozen Frontline",
        type: "movie",
        tags: ["action", "drama", "cinema"],
        genre: "Chiến Tranh",
        country: "Nga",
        year: 2025,
        status: "N/A",
        quality: "HD",
        lang: "Vietsub",
        rating: 7.3,
        views: 278451,
        poster: "https://image.tmdb.org/t/p/w500/bcM2Tl5HlsvPBnL8DKP9Ie6vU4r.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg",
        description: "Một đơn vị nhỏ mắc kẹt giữa vùng băng tuyết phải giữ phòng tuyến cho đến khi tín hiệu cứu viện xuất hiện.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    },
    {
        id: 32,
        title: "Kho Báu Đảo Sương Mù",
        original: "Treasure of Mist Island",
        type: "series",
        tags: ["adventure", "comedy"],
        genre: "Phiêu Lưu",
        country: "Âu Mỹ",
        year: 2026,
        status: "Tập 3/10",
        quality: "HD",
        lang: "Vietsub",
        rating: 7.6,
        views: 364908,
        poster: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
        backdrop: "https://image.tmdb.org/t/p/w1280/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg",
        description: "Một bản đồ rách dẫn nhóm thám hiểm đến hòn đảo phủ sương, nơi kho báu chỉ là phần nổi của bí mật lớn hơn.",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ"
    }
];
